"""create audit_log table

Revision ID: 11b37e0ff189
Revises: d380213499d7
Create Date: 2026-09-25 07:28:16.851849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b37e0ff189'
down_revision: Union[str, Sequence[str], None] = 'd380213499d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('proposed_payload_json', sa.String(), nullable=False),
    sa.Column('human_decision', sa.String(length=20), nullable=False),
    sa.Column('final_payload_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
