"""add project_id to task_jira_links and audit_log

Revision ID: 5f3951d26122
Revises: 9e8d811ac9f0
Create Date: 2026-10-02 17:09:39.019270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3951d26122'
down_revision: Union[str, Sequence[str], None] = '9e8d811ac9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
