"""create task_jira_links table

Revision ID: 62730ca602f4
Revises: 0fc92262ee58
Create Date: 2026-09-12 13:07:46.930672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62730ca602f4'
down_revision: Union[str, Sequence[str], None] = '0fc92262ee58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_jira_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=False),
    sa.Column('task_title', sa.String(length=500), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key', 'task_title', name='uq_project_task_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_jira_links')
    # ### end Alembic commands ###
