"""add project_id to task_jira_links and audit_log

Revision ID: 9e8d811ac9f0
Revises: cf0b1e3abbdd
Create Date: 2026-10-02 17:08:07.633220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8d811ac9f0'
down_revision: Union[str, Sequence[str], None] = 'cf0b1e3abbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('task_jira_links', sa.Column('project_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_jira_links', 'project_id')
    op.drop_column('audit_log', 'project_id')
    # ### end Alembic commands ###
