"""create projects table

Revision ID: cf0b1e3abbdd
Revises: 11b37e0ff189
Create Date: 2026-10-02 17:02:55.962848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0b1e3abbdd'
down_revision: Union[str, Sequence[str], None] = '11b37e0ff189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jira_project_key', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=2000), nullable=False),
    sa.Column('deadline', sa.String(length=100), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
