"""add jira_issue_id to task_jira_links

Revision ID: d380213499d7
Revises: 62730ca602f4
Create Date: 2026-09-13 00:14:00.404016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd380213499d7'
down_revision: Union[str, Sequence[str], None] = '62730ca602f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing links predate Jira numeric IDs; the temporary default keeps the
    # SQLite migration valid until new links are written with real IDs.
    op.add_column(
        'task_jira_links',
        sa.Column(
            'jira_issue_id',
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_jira_links', 'jira_issue_id')
    # ### end Alembic commands ###
